[build-system]
requires = ["setuptools >= 65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "saturnin"
version = "0.7.1"
description = "Firebird Butler platform for Python"
readme = "README.rst"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [{ name = "Pavel Císař", email = "pcisar@users.sourceforge.net"}]
keywords = ["Saturnin", "Firebird", "Butler", "Platform", "ZeroMQ"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Topic :: System :: Systems Administration",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Logging",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Object Brokering"
    ]
dependencies = [
    "build",
    "toml",
    "packaging >= 21.0",
    "pyzmq>=24.0.0",
    "protobuf>=4.21.0, <5",
    "psutil>=5.9.0",
    "firebird-butler-protobuf>=0.3.1",
    "firebird-base>=1.4.0, <2"
    ]

[project.urls]
Home = "http://firebirdsql.org/en/saturnin/"
Documentation = "https://saturnin.rtfd.io"
"Bug Reports" = "https://github.com/FirebirdSQL/saturnin/issues"
Funding = "https://www.firebirdsql.org/en/donate/"
Source = "https://github.com/FirebirdSQL/saturnin"

[project.scripts]
saturnin = "saturnin._scripts.cli:main"
saturnin-site = "saturnin._scripts.site:main"
saturnin-pkg = "saturnin._scripts.pkg:main"
saturnin-daemon = "saturnin._scripts.daemon:main"
saturnin-service = "saturnin._scripts.svcrun:main"
saturnin-bundle = "saturnin._scripts.bundlerun:main"

[project.entry-points."saturnin.commands.cli"]
"saturnin.start" = "saturnin._scripts.commands.cli:StartCommand"
"saturnin.stop" = "saturnin._scripts.commands.cli:StopCommand"
"saturnin.list" = "saturnin._scripts.commands.cli:ListCommand"
"saturnin.help" = "saturnin.lib.command:HelpCommand"

[project.entry-points."saturnin.commands.pkg"]
"saturnin.install" = "saturnin._scripts.commands.pkg:InstallCommand"
"saturnin.uninstall" = "saturnin._scripts.commands.pkg:UninstallCommand"
"saturnin.list" = "saturnin._scripts.commands.pkg:ListCommand"
"saturnin.pip" = "saturnin._scripts.commands.pkg:PipCommand"
"saturnin.help" = "saturnin.lib.command:HelpCommand"

[project.entry-points."saturnin.commands.site"]
"saturnin.init" = "saturnin._scripts.commands.site:InitCommand"
"saturnin.create" = "saturnin._scripts.commands.site:CreateCommand"
"saturnin.edit" = "saturnin._scripts.commands.site:EditCommand"
"saturnin.list" = "saturnin._scripts.commands.site:ListCommand"
"saturnin.help" = "saturnin.lib.command:HelpCommand"
