# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturnin/protobuf/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='saturnin/protobuf/common.proto',
  package='saturnin.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1esaturnin/protobuf/common.proto\x12\x11saturnin.protobuf\x1a\x1cgoogle/protobuf/struct.proto\"H\n\rGenDataRecord\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"C\n\x0eGenDataPackage\x12\x31\n\x07records\x18\x01 \x03(\x0b\x32 .saturnin.protobuf.GenDataRecord*S\n\x11\x45xecutionModeEnum\x12\x11\n\rEXEC_MODE_ANY\x10\x00\x12\x14\n\x10\x45XEC_MODE_THREAD\x10\x01\x12\x15\n\x11\x45XEC_MODE_PROCESS\x10\x02*\xbf\x01\n\x0fServiceTypeEnum\x12\x14\n\x10SVC_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16SVC_TYPE_DATA_PROVIDER\x10\x01\x12\x18\n\x14SVC_TYPE_DATA_FILTER\x10\x02\x12\x1a\n\x16SVC_TYPE_DATA_CONSUMER\x10\x03\x12\x17\n\x13SVC_TYPE_PROCESSING\x10\x04\x12\x15\n\x11SVC_TYPE_EXECUTOR\x10\x05\x12\x14\n\x10SVC_TYPE_CONTROL\x10\x06*\xca\x01\n\x15ServiceFacilitiesEnum\x12\x15\n\x11SVC_FACILITY_NONE\x10\x00\x12\x1c\n\x18SVC_FACILITY_FBSP_SOCKET\x10\x01\x12\x1d\n\x19SVC_FACILITY_INPUT_SERVER\x10\x02\x12\x1d\n\x19SVC_FACILITY_INPUT_CLIENT\x10\x03\x12\x1e\n\x1aSVC_FACILITY_OUTPUT_SERVER\x10\x04\x12\x1e\n\x1aSVC_FACILITY_OUTPUT_CLIENT\x10\x05*y\n\rSeverityLevel\x12\x14\n\x10SEVERITY_UNKNOWN\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x14\n\x10SEVERITY_WARNING\x10\x02\x12\x12\n\x0eSEVERITY_ERROR\x10\x03\x12\x15\n\x11SEVERITY_CRITICAL\x10\x04\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])

_EXECUTIONMODEENUM = _descriptor.EnumDescriptor(
  name='ExecutionModeEnum',
  full_name='saturnin.protobuf.ExecutionModeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXEC_MODE_ANY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXEC_MODE_THREAD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXEC_MODE_PROCESS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=309,
)
_sym_db.RegisterEnumDescriptor(_EXECUTIONMODEENUM)

ExecutionModeEnum = enum_type_wrapper.EnumTypeWrapper(_EXECUTIONMODEENUM)
_SERVICETYPEENUM = _descriptor.EnumDescriptor(
  name='ServiceTypeEnum',
  full_name='saturnin.protobuf.ServiceTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_DATA_PROVIDER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_DATA_FILTER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_DATA_CONSUMER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_PROCESSING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_EXECUTOR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_CONTROL', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=312,
  serialized_end=503,
)
_sym_db.RegisterEnumDescriptor(_SERVICETYPEENUM)

ServiceTypeEnum = enum_type_wrapper.EnumTypeWrapper(_SERVICETYPEENUM)
_SERVICEFACILITIESENUM = _descriptor.EnumDescriptor(
  name='ServiceFacilitiesEnum',
  full_name='saturnin.protobuf.ServiceFacilitiesEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SVC_FACILITY_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_FACILITY_FBSP_SOCKET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_FACILITY_INPUT_SERVER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_FACILITY_INPUT_CLIENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_FACILITY_OUTPUT_SERVER', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVC_FACILITY_OUTPUT_CLIENT', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=506,
  serialized_end=708,
)
_sym_db.RegisterEnumDescriptor(_SERVICEFACILITIESENUM)

ServiceFacilitiesEnum = enum_type_wrapper.EnumTypeWrapper(_SERVICEFACILITIESENUM)
_SEVERITYLEVEL = _descriptor.EnumDescriptor(
  name='SeverityLevel',
  full_name='saturnin.protobuf.SeverityLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_INFO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_WARNING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_CRITICAL', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=710,
  serialized_end=831,
)
_sym_db.RegisterEnumDescriptor(_SEVERITYLEVEL)

SeverityLevel = enum_type_wrapper.EnumTypeWrapper(_SEVERITYLEVEL)
EXEC_MODE_ANY = 0
EXEC_MODE_THREAD = 1
EXEC_MODE_PROCESS = 2
SVC_TYPE_UNKNOWN = 0
SVC_TYPE_DATA_PROVIDER = 1
SVC_TYPE_DATA_FILTER = 2
SVC_TYPE_DATA_CONSUMER = 3
SVC_TYPE_PROCESSING = 4
SVC_TYPE_EXECUTOR = 5
SVC_TYPE_CONTROL = 6
SVC_FACILITY_NONE = 0
SVC_FACILITY_FBSP_SOCKET = 1
SVC_FACILITY_INPUT_SERVER = 2
SVC_FACILITY_INPUT_CLIENT = 3
SVC_FACILITY_OUTPUT_SERVER = 4
SVC_FACILITY_OUTPUT_CLIENT = 5
SEVERITY_UNKNOWN = 0
SEVERITY_INFO = 1
SEVERITY_WARNING = 2
SEVERITY_ERROR = 3
SEVERITY_CRITICAL = 4



_GENDATARECORD = _descriptor.Descriptor(
  name='GenDataRecord',
  full_name='saturnin.protobuf.GenDataRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='saturnin.protobuf.GenDataRecord.sequence', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='saturnin.protobuf.GenDataRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=155,
)


_GENDATAPACKAGE = _descriptor.Descriptor(
  name='GenDataPackage',
  full_name='saturnin.protobuf.GenDataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='saturnin.protobuf.GenDataPackage.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=224,
)

_GENDATARECORD.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GENDATAPACKAGE.fields_by_name['records'].message_type = _GENDATARECORD
DESCRIPTOR.message_types_by_name['GenDataRecord'] = _GENDATARECORD
DESCRIPTOR.message_types_by_name['GenDataPackage'] = _GENDATAPACKAGE
DESCRIPTOR.enum_types_by_name['ExecutionModeEnum'] = _EXECUTIONMODEENUM
DESCRIPTOR.enum_types_by_name['ServiceTypeEnum'] = _SERVICETYPEENUM
DESCRIPTOR.enum_types_by_name['ServiceFacilitiesEnum'] = _SERVICEFACILITIESENUM
DESCRIPTOR.enum_types_by_name['SeverityLevel'] = _SEVERITYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenDataRecord = _reflection.GeneratedProtocolMessageType('GenDataRecord', (_message.Message,), {
  'DESCRIPTOR' : _GENDATARECORD,
  '__module__' : 'saturnin.protobuf.common_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.protobuf.GenDataRecord)
  })
_sym_db.RegisterMessage(GenDataRecord)

GenDataPackage = _reflection.GeneratedProtocolMessageType('GenDataPackage', (_message.Message,), {
  'DESCRIPTOR' : _GENDATAPACKAGE,
  '__module__' : 'saturnin.protobuf.common_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.protobuf.GenDataPackage)
  })
_sym_db.RegisterMessage(GenDataPackage)


# @@protoc_insertion_point(module_scope)
