# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturnin/protobuf/fblog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from saturnin.protobuf import common_pb2 as saturnin_dot_protobuf_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='saturnin/protobuf/fblog.proto',
  package='saturnin.protobuf.fblog',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dsaturnin/protobuf/fblog.proto\x12\x17saturnin.protobuf.fblog\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1esaturnin/protobuf/common.proto\"\xff\x01\n\x08LogEntry\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x05level\x18\x03 \x01(\x0e\x32 .saturnin.protobuf.SeverityLevel\x12\x0c\n\x04\x63ode\x18\x04 \x01(\r\x12;\n\x08\x66\x61\x63ility\x18\x05 \x01(\x0e\x32).saturnin.protobuf.fblog.FirebirdFacility\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\'\n\x06params\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct*\x8b\x02\n\x10\x46irebirdFacility\x12\x14\n\x10\x46\x41\x43ILITY_UNKNOWN\x10\x00\x12\x13\n\x0f\x46\x41\x43ILITY_SYSTEM\x10\x01\x12\x13\n\x0f\x46\x41\x43ILITY_CONFIG\x10\x02\x12\x11\n\rFACILITY_INTL\x10\x03\x12\x13\n\x0f\x46\x41\x43ILITY_FILEIO\x10\x04\x12\x11\n\rFACILITY_USER\x10\x05\x12\x17\n\x13\x46\x41\x43ILITY_VALIDATION\x10\x06\x12\x12\n\x0e\x46\x41\x43ILITY_SWEEP\x10\x07\x12\x13\n\x0f\x46\x41\x43ILITY_PLUGIN\x10\x08\x12\x15\n\x11\x46\x41\x43ILITY_GUARDIAN\x10\t\x12\x10\n\x0c\x46\x41\x43ILITY_NET\x10\n\x12\x11\n\rFACILITY_AUTH\x10\x0b\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,saturnin_dot_protobuf_dot_common__pb2.DESCRIPTOR,])

_FIREBIRDFACILITY = _descriptor.EnumDescriptor(
  name='FirebirdFacility',
  full_name='saturnin.protobuf.fblog.FirebirdFacility',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FACILITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_SYSTEM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_CONFIG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_INTL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_FILEIO', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_USER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_VALIDATION', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_SWEEP', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_PLUGIN', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_GUARDIAN', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_NET', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACILITY_AUTH', index=11, number=11,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=412,
  serialized_end=679,
)
_sym_db.RegisterEnumDescriptor(_FIREBIRDFACILITY)

FirebirdFacility = enum_type_wrapper.EnumTypeWrapper(_FIREBIRDFACILITY)
FACILITY_UNKNOWN = 0
FACILITY_SYSTEM = 1
FACILITY_CONFIG = 2
FACILITY_INTL = 3
FACILITY_FILEIO = 4
FACILITY_USER = 5
FACILITY_VALIDATION = 6
FACILITY_SWEEP = 7
FACILITY_PLUGIN = 8
FACILITY_GUARDIAN = 9
FACILITY_NET = 10
FACILITY_AUTH = 11



_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='saturnin.protobuf.fblog.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='saturnin.protobuf.fblog.LogEntry.origin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='saturnin.protobuf.fblog.LogEntry.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='saturnin.protobuf.fblog.LogEntry.level', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='saturnin.protobuf.fblog.LogEntry.code', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='facility', full_name='saturnin.protobuf.fblog.LogEntry.facility', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='saturnin.protobuf.fblog.LogEntry.message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='saturnin.protobuf.fblog.LogEntry.params', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=409,
)

_LOGENTRY.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LOGENTRY.fields_by_name['level'].enum_type = saturnin_dot_protobuf_dot_common__pb2._SEVERITYLEVEL
_LOGENTRY.fields_by_name['facility'].enum_type = _FIREBIRDFACILITY
_LOGENTRY.fields_by_name['params'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.enum_types_by_name['FirebirdFacility'] = _FIREBIRDFACILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'saturnin.protobuf.fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.protobuf.fblog.LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)


# @@protoc_insertion_point(module_scope)
