# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fblog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from saturnin.protobuf import saturnin_pb2 as saturnin_dot_protobuf_dot_saturnin__pb2
try:
  saturnin_dot_sdk_dot_fbsp__pb2 = saturnin_dot_protobuf_dot_saturnin__pb2.saturnin_dot_sdk_dot_fbsp__pb2
except AttributeError:
  saturnin_dot_sdk_dot_fbsp__pb2 = saturnin_dot_protobuf_dot_saturnin__pb2.saturnin.sdk.fbsp_pb2

from google.protobuf.struct_pb2 import *
from google.protobuf.timestamp_pb2 import *
from saturnin.protobuf.saturnin_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='fblog.proto',
  package='saturnin.fblog',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x66\x62log.proto\x12\x0esaturnin.fblog\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a saturnin/protobuf/saturnin.proto\"e\n\x10\x46irebirdLogEntry\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x03 \x01(\t\"x\n\tLogSource\x12\x12\n\x08\x66ilespec\x18\x01 \x01(\tH\x00\x12)\n\x06server\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12\"\n\x04pipe\x18\x03 \x01(\x0b\x32\x12.saturnin.DataPipeH\x00\x42\x08\n\x06source\"`\n\x0eRequestMonitor\x12)\n\x06source\x18\x01 \x01(\x0b\x32\x19.saturnin.fblog.LogSource\x12#\n\x07push_to\x18\x02 \x01(\x0b\x32\x12.saturnin.DataPipe\"@\n\x0cReplyMonitor\x12\x0e\n\x06handle\x18\x01 \x01(\x05\x12 \n\x04pipe\x18\x02 \x01(\x0b\x32\x12.saturnin.DataPipe\"$\n\x12RequestStopMonitor\x12\x0e\n\x06handle\x18\x01 \x01(\x05\"`\n\x0eRequestEntries\x12)\n\x06source\x18\x01 \x01(\x0b\x32\x19.saturnin.fblog.LogSource\x12#\n\x07push_to\x18\x02 \x01(\x0b\x32\x12.saturnin.DataPipeP\x00P\x01P\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,saturnin_dot_protobuf_dot_saturnin__pb2.DESCRIPTOR,],
  public_dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,saturnin_dot_protobuf_dot_saturnin__pb2.DESCRIPTOR,])




_FIREBIRDLOGENTRY = _descriptor.Descriptor(
  name='FirebirdLogEntry',
  full_name='saturnin.fblog.FirebirdLogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_id', full_name='saturnin.fblog.FirebirdLogEntry.source_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='saturnin.fblog.FirebirdLogEntry.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='saturnin.fblog.FirebirdLogEntry.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=229,
)


_LOGSOURCE = _descriptor.Descriptor(
  name='LogSource',
  full_name='saturnin.fblog.LogSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filespec', full_name='saturnin.fblog.LogSource.filespec', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server', full_name='saturnin.fblog.LogSource.server', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pipe', full_name='saturnin.fblog.LogSource.pipe', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='source', full_name='saturnin.fblog.LogSource.source',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=231,
  serialized_end=351,
)


_REQUESTMONITOR = _descriptor.Descriptor(
  name='RequestMonitor',
  full_name='saturnin.fblog.RequestMonitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='saturnin.fblog.RequestMonitor.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='push_to', full_name='saturnin.fblog.RequestMonitor.push_to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=449,
)


_REPLYMONITOR = _descriptor.Descriptor(
  name='ReplyMonitor',
  full_name='saturnin.fblog.ReplyMonitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='saturnin.fblog.ReplyMonitor.handle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pipe', full_name='saturnin.fblog.ReplyMonitor.pipe', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=515,
)


_REQUESTSTOPMONITOR = _descriptor.Descriptor(
  name='RequestStopMonitor',
  full_name='saturnin.fblog.RequestStopMonitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='saturnin.fblog.RequestStopMonitor.handle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=553,
)


_REQUESTENTRIES = _descriptor.Descriptor(
  name='RequestEntries',
  full_name='saturnin.fblog.RequestEntries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='saturnin.fblog.RequestEntries.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='push_to', full_name='saturnin.fblog.RequestEntries.push_to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=651,
)

_FIREBIRDLOGENTRY.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LOGSOURCE.fields_by_name['server'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_LOGSOURCE.fields_by_name['pipe'].message_type = saturnin_dot_protobuf_dot_saturnin__pb2._DATAPIPE
_LOGSOURCE.oneofs_by_name['source'].fields.append(
  _LOGSOURCE.fields_by_name['filespec'])
_LOGSOURCE.fields_by_name['filespec'].containing_oneof = _LOGSOURCE.oneofs_by_name['source']
_LOGSOURCE.oneofs_by_name['source'].fields.append(
  _LOGSOURCE.fields_by_name['server'])
_LOGSOURCE.fields_by_name['server'].containing_oneof = _LOGSOURCE.oneofs_by_name['source']
_LOGSOURCE.oneofs_by_name['source'].fields.append(
  _LOGSOURCE.fields_by_name['pipe'])
_LOGSOURCE.fields_by_name['pipe'].containing_oneof = _LOGSOURCE.oneofs_by_name['source']
_REQUESTMONITOR.fields_by_name['source'].message_type = _LOGSOURCE
_REQUESTMONITOR.fields_by_name['push_to'].message_type = saturnin_dot_protobuf_dot_saturnin__pb2._DATAPIPE
_REPLYMONITOR.fields_by_name['pipe'].message_type = saturnin_dot_protobuf_dot_saturnin__pb2._DATAPIPE
_REQUESTENTRIES.fields_by_name['source'].message_type = _LOGSOURCE
_REQUESTENTRIES.fields_by_name['push_to'].message_type = saturnin_dot_protobuf_dot_saturnin__pb2._DATAPIPE
DESCRIPTOR.message_types_by_name['FirebirdLogEntry'] = _FIREBIRDLOGENTRY
DESCRIPTOR.message_types_by_name['LogSource'] = _LOGSOURCE
DESCRIPTOR.message_types_by_name['RequestMonitor'] = _REQUESTMONITOR
DESCRIPTOR.message_types_by_name['ReplyMonitor'] = _REPLYMONITOR
DESCRIPTOR.message_types_by_name['RequestStopMonitor'] = _REQUESTSTOPMONITOR
DESCRIPTOR.message_types_by_name['RequestEntries'] = _REQUESTENTRIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirebirdLogEntry = _reflection.GeneratedProtocolMessageType('FirebirdLogEntry', (_message.Message,), dict(
  DESCRIPTOR = _FIREBIRDLOGENTRY,
  __module__ = 'fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.fblog.FirebirdLogEntry)
  ))
_sym_db.RegisterMessage(FirebirdLogEntry)

LogSource = _reflection.GeneratedProtocolMessageType('LogSource', (_message.Message,), dict(
  DESCRIPTOR = _LOGSOURCE,
  __module__ = 'fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.fblog.LogSource)
  ))
_sym_db.RegisterMessage(LogSource)

RequestMonitor = _reflection.GeneratedProtocolMessageType('RequestMonitor', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMONITOR,
  __module__ = 'fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.fblog.RequestMonitor)
  ))
_sym_db.RegisterMessage(RequestMonitor)

ReplyMonitor = _reflection.GeneratedProtocolMessageType('ReplyMonitor', (_message.Message,), dict(
  DESCRIPTOR = _REPLYMONITOR,
  __module__ = 'fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.fblog.ReplyMonitor)
  ))
_sym_db.RegisterMessage(ReplyMonitor)

RequestStopMonitor = _reflection.GeneratedProtocolMessageType('RequestStopMonitor', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTSTOPMONITOR,
  __module__ = 'fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.fblog.RequestStopMonitor)
  ))
_sym_db.RegisterMessage(RequestStopMonitor)

RequestEntries = _reflection.GeneratedProtocolMessageType('RequestEntries', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTENTRIES,
  __module__ = 'fblog_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.fblog.RequestEntries)
  ))
_sym_db.RegisterMessage(RequestEntries)


# @@protoc_insertion_point(module_scope)
