# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturnin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from saturnin.sdk import fbsp_pb2 as saturnin_dot_sdk_dot_fbsp__pb2

from saturnin.sdk.fbsp_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='saturnin.proto',
  package='firebird.saturnin',
  syntax='proto3',
  serialized_pb=_b('\n\x0esaturnin.proto\x12\x11\x66irebird.saturnin\x1a\x19google/protobuf/any.proto\x1a\x17saturnin/sdk/fbsp.proto\"J\n\nDependency\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.firebird.saturnin.DependencyType\x12\x0b\n\x03uid\x18\x02 \x01(\x0c\")\n\x0bRequestCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"t\n\x13InterfaceDescriptor\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08revision\x18\x03 \x01(\r\x12\x30\n\x08requests\x18\x04 \x03(\x0b\x32\x1e.firebird.saturnin.RequestCode\"\xdb\x01\n\x10InstalledService\x12\x33\n\x05\x61gent\x18\x01 \x01(\x0b\x32$.firebird.butler.AgentIdentification\x12\x33\n\x03\x61pi\x18\x02 \x03(\x0b\x32&.firebird.saturnin.InterfaceDescriptor\x12\x33\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32\x1d.firebird.saturnin.Dependency\x12(\n\nsupplement\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any*H\n\x0e\x44\x65pendencyType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08REQUIRED\x10\x01\x12\r\n\tPREFERRED\x10\x02\x12\x0c\n\x08OPTIONAL\x10\x03\x42\x39\n\x15org.firebird.saturninB\rSaturninProtoP\x01\xa2\x02\x03SPB\xaa\x02\x08SaturninP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,saturnin_dot_sdk_dot_fbsp__pb2.DESCRIPTOR,],
  public_dependencies=[saturnin_dot_sdk_dot_fbsp__pb2.DESCRIPTOR,])

_DEPENDENCYTYPE = _descriptor.EnumDescriptor(
  name='DependencyType',
  full_name='firebird.saturnin.DependencyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUIRED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREFERRED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPTIONAL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=548,
  serialized_end=620,
)
_sym_db.RegisterEnumDescriptor(_DEPENDENCYTYPE)

DependencyType = enum_type_wrapper.EnumTypeWrapper(_DEPENDENCYTYPE)
UNKNOWN = 0
REQUIRED = 1
PREFERRED = 2
OPTIONAL = 3



_DEPENDENCY = _descriptor.Descriptor(
  name='Dependency',
  full_name='firebird.saturnin.Dependency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='firebird.saturnin.Dependency.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='firebird.saturnin.Dependency.uid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=163,
)


_REQUESTCODE = _descriptor.Descriptor(
  name='RequestCode',
  full_name='firebird.saturnin.RequestCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='firebird.saturnin.RequestCode.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='firebird.saturnin.RequestCode.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=206,
)


_INTERFACEDESCRIPTOR = _descriptor.Descriptor(
  name='InterfaceDescriptor',
  full_name='firebird.saturnin.InterfaceDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='firebird.saturnin.InterfaceDescriptor.uid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='firebird.saturnin.InterfaceDescriptor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='firebird.saturnin.InterfaceDescriptor.revision', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='firebird.saturnin.InterfaceDescriptor.requests', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=324,
)


_INSTALLEDSERVICE = _descriptor.Descriptor(
  name='InstalledService',
  full_name='firebird.saturnin.InstalledService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='firebird.saturnin.InstalledService.agent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api', full_name='firebird.saturnin.InstalledService.api', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='firebird.saturnin.InstalledService.dependencies', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='firebird.saturnin.InstalledService.supplement', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=546,
)

_DEPENDENCY.fields_by_name['type'].enum_type = _DEPENDENCYTYPE
_INTERFACEDESCRIPTOR.fields_by_name['requests'].message_type = _REQUESTCODE
_INSTALLEDSERVICE.fields_by_name['agent'].message_type = saturnin_dot_sdk_dot_fbsp__pb2._AGENTIDENTIFICATION
_INSTALLEDSERVICE.fields_by_name['api'].message_type = _INTERFACEDESCRIPTOR
_INSTALLEDSERVICE.fields_by_name['dependencies'].message_type = _DEPENDENCY
_INSTALLEDSERVICE.fields_by_name['supplement'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Dependency'] = _DEPENDENCY
DESCRIPTOR.message_types_by_name['RequestCode'] = _REQUESTCODE
DESCRIPTOR.message_types_by_name['InterfaceDescriptor'] = _INTERFACEDESCRIPTOR
DESCRIPTOR.message_types_by_name['InstalledService'] = _INSTALLEDSERVICE
DESCRIPTOR.enum_types_by_name['DependencyType'] = _DEPENDENCYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dependency = _reflection.GeneratedProtocolMessageType('Dependency', (_message.Message,), dict(
  DESCRIPTOR = _DEPENDENCY,
  __module__ = 'saturnin_pb2'
  # @@protoc_insertion_point(class_scope:firebird.saturnin.Dependency)
  ))
_sym_db.RegisterMessage(Dependency)

RequestCode = _reflection.GeneratedProtocolMessageType('RequestCode', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTCODE,
  __module__ = 'saturnin_pb2'
  # @@protoc_insertion_point(class_scope:firebird.saturnin.RequestCode)
  ))
_sym_db.RegisterMessage(RequestCode)

InterfaceDescriptor = _reflection.GeneratedProtocolMessageType('InterfaceDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACEDESCRIPTOR,
  __module__ = 'saturnin_pb2'
  # @@protoc_insertion_point(class_scope:firebird.saturnin.InterfaceDescriptor)
  ))
_sym_db.RegisterMessage(InterfaceDescriptor)

InstalledService = _reflection.GeneratedProtocolMessageType('InstalledService', (_message.Message,), dict(
  DESCRIPTOR = _INSTALLEDSERVICE,
  __module__ = 'saturnin_pb2'
  # @@protoc_insertion_point(class_scope:firebird.saturnin.InstalledService)
  ))
_sym_db.RegisterMessage(InstalledService)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025org.firebird.saturninB\rSaturninProtoP\001\242\002\003SPB\252\002\010Saturnin'))
# @@protoc_insertion_point(module_scope)
